import NextAuthProviders from "@/providers/NextAuthProviders";
import {
  Geist,
  Geist_Mono,
  Italianno,
  Quicksand,
  Roboto,
} from "next/font/google";
import { ToastContainer } from "react-toastify";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
const italiannoo = Italianno({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-italianno",
});
const quicksand = Quicksand({
  weight: '500',
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${quicksand.className} ${geistMono.variable} antialiased`}
      >
        <NextAuthProviders>

      
        <Navbar />
        {children}
        <Footer/>
         <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          pauseOnHover
        />
          </NextAuthProviders>
      </body>
    </html>
  );
}
